[General]
key_pmi=8188114541
key_pmi_invite_msg="Harshal Gunjal is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Harshal Gunjal's Personal Meeting Room\r\nJoin Zoom Meeting\r\nhttps://us05web.zoom.us/j/8188114541?pwd=7gDObE3pgORwQZiVZUXRS3siz0qaaX.1\r\n\r\nMeeting ID: 818 811 4541\r\nPasscode: E23D1U\r\n\r\n"
