github.com:
    users:
        HarshalGunjalOp:
            oauth_token: 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
    git_protocol: https
    user: HarshalGunjalOp
    oauth_token: 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
