# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141515)
$foreground = rgb(E6F1F3)
$color0 = rgb(3B3C3C)
$color1 = rgb(0D1010)
$color2 = rgb(101618)
$color3 = rgb(26424F)
$color4 = rgb(38687E)
$color5 = rgb(3E758E)
$color6 = rgb(8BA2A7)
$color7 = rgb(D4E3E6)
$color8 = rgb(949FA1)
$color9 = rgb(121516)
$color10 = rgb(161D20)
$color11 = rgb(325869)
$color12 = rgb(4A8BA8)
$color13 = rgb(529CBD)
$color14 = rgb(B9D8DE)
$color15 = rgb(D4E3E6)
