# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1B24)
$foreground = rgb(F6E8E2)
$color0 = rgb(43424B)
$color1 = rgb(384D78)
$color2 = rgb(3F5179)
$color3 = rgb(726D7D)
$color4 = rgb(50749D)
$color5 = rgb(A58981)
$color6 = rgb(AC8D82)
$color7 = rgb(EAD5CE)
$color8 = rgb(A49590)
$color9 = rgb(4A67A0)
$color10 = rgb(546CA1)
$color11 = rgb(9891A6)
$color12 = rgb(6B9AD1)
$color13 = rgb(DCB7AC)
$color14 = rgb(E6BCAD)
$color15 = rgb(EAD5CE)
