# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(191C1C)
$foreground = rgb(E8F4F5)
$color0 = rgb(3F4343)
$color1 = rgb(324C4F)
$color2 = rgb(325559)
$color3 = rgb(517578)
$color4 = rgb(5B8286)
$color5 = rgb(A7A364)
$color6 = rgb(8DA8AA)
$color7 = rgb(D5E7E8)
$color8 = rgb(95A2A3)
$color9 = rgb(436669)
$color10 = rgb(427177)
$color11 = rgb(6B9BA0)
$color12 = rgb(79ADB2)
$color13 = rgb(DFD985)
$color14 = rgb(BCDFE3)
$color15 = rgb(D5E7E8)
