# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C7CDD0
background         #222324
cursor             #828B90

active_tab_foreground     #222324
active_tab_background     #C7CDD0
inactive_tab_foreground   #C7CDD0
inactive_tab_background   #222324

active_border_color   #C7CDD0
inactive_border_color #222324
bell_border_color     #262E32

color0      #48494A
color1		#262E32
color2		#2E373C
color3		#364147
color4		#3E4A51
color5		#47535B
color6		#47535B
color7		#A6AFB4
color8		#747A7E
color9		#333D43
color10		#3E4A51
color11		#48565E
color12		#53636C
color13		#5E6F79
color14		#5E6F79
color15		#A6AFB4
