# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E8F4F5
background         #191C1C
cursor             #95B3B6

active_tab_foreground     #191C1C
active_tab_background     #E8F4F5
inactive_tab_foreground   #E8F4F5
inactive_tab_background   #191C1C

active_border_color   #E8F4F5
inactive_border_color #191C1C
bell_border_color     #324C4F

color0      #3F4343
color1		#324C4F
color2		#325559
color3		#517578
color4		#5B8286
color5		#A7A364
color6		#8DA8AA
color7		#D5E7E8
color8		#95A2A3
color9		#436669
color10		#427177
color11		#6B9BA0
color12		#79ADB2
color13		#DFD985
color14		#BCDFE3
color15		#D5E7E8
