# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6E8E2
background         #1C1B24
cursor             #A5AAC2

active_tab_foreground     #1C1B24
active_tab_background     #F6E8E2
inactive_tab_foreground   #F6E8E2
inactive_tab_background   #1C1B24

active_border_color   #F6E8E2
inactive_border_color #1C1B24
bell_border_color     #384D78

color0      #43424B
color1		#384D78
color2		#3F5179
color3		#726D7D
color4		#50749D
color5		#A58981
color6		#AC8D82
color7		#EAD5CE
color8		#A49590
color9		#4A67A0
color10		#546CA1
color11		#9891A6
color12		#6B9AD1
color13		#DCB7AC
color14		#E6BCAD
color15		#EAD5CE
