[FileDialog]
history=file:///home/harshal/Downloads, file:///home/harshal/VirtualBox VMs, file:///home/harshal/SQLiteStudio, file:///home/harshal/SQLiteStudio/databases, file:///opt/zoom, file:///home/harshal/Pictures/Screenshots
lastVisited=file:///home/harshal/Pictures/Screenshots
qtVersion=6.9.1
shortcuts=file:, file:///home/harshal
sidebarWidth=58
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\xbd\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\x30\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\0\xbb\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
